moduleOneA = {
    "to apply": "anwenden",
    "to design": "entwerfen, konstruieren",
    "website": "Website, Internetseite",
    "to integrate": "integrieren",
    "database": "Datenbank",
    "focus": "Schwerpunkt",
    "design": "Gestaltung, Design",
    "to advise": "beraten",
    "functionality": "Funktionalität",
    "option": "Alternative, Möglichkeit",
    "benefit": "Leistung, Nutzen",
    "overall": "gesamt",
    "suggestion": "Vorschlag",
    "impact": "Wirkung, Einfluss",
    "performance": "Ergebnis, Erfolg",
    "thorough": "gründlich",
    "analytical": "analytisch",
    "verbal": "mündlich",
    "graphic": "graphisch",
    "to troubleshoot": "Fehler beheben",
    "maintenance": "Wartung",
    "LAN (local area network)": "lokales Netzwerk",
    "WAN (wide area network)": "Weitverkehrsnetzwerk",
    "implementation": "Einführung, Umsetzung, Implementierung",
    "to recommend": "empfehlen",
    "to schedule": "anberaumen",
    "to handle": "umgehen mit",
    "confidential": "vertraulich",
    "broad": "breit angelegt",
    "several": "mehrere",
    "to recognize": "erkennen, anerkennen",
    "career": "Beruf, Laufbahn, Karriere",
    "to outline": "umreißen, skizzieren",
    "systems analyst": "Systemberater",
    "findings": "Ergebnisse",
    "job title": "Berufsbezeichnung",
    "to swap": "tauschen",
    "confident": "sicher, selbstbewusst",
    "appropriate": "angemessen, passend",
    "existing": "bestehend",
    "trade fair": "Messe",
    "job fair": "Jobmesse"

}

amazonSheet ={
    "high-rise": "Hochhaus",
    "to range": "reichen, sich bewegen zwischen",
    "reportedly": "angeblich, wie gemeldet",
    "recent": "neu, letzte",
    "to promote": "verbreiten",
    "discriminatory practice": "diskriminierende Praxis",
    "retail": "Einzelhandel",
    "to debit": "abbuchen",
    "receipt": "Beleg, Quittung",
    "to dive into": "eintauchen",
    "mock": "Probe- / Schein-",
    "bottleneck": "Nadelöhr, Flaschenhals",
    "to defeat": "zerschlagen, besiegen",
    "intention": "Absicht",
    "line": "(Warte-)Schlange",
    "to tinker": "tüfteln",
    "counter": "Theke",
    "holdup": "Verzögerung",
    "to shrink": "schrumpfen",
    "bullish": "stur",
    "to fall short of": "hinter etwas zurückbleiben",
    "attempt": "Versuch",
    "grocery": "Lebensmittel",
    "according to": "laut",
    "permit": "Zulassung",
    "to abandon": "verlassen",
}


module1B ={
    "apprenticeship": "Lehre, Ausbildung",
    "tutor": "Klassenlehrer, Betreuer",
    "organigram": "Organigramm",
    "curious": "neugierig",
    "major": "Haupt-, bedeutend",
    "separate": "einzeln, gesondert",
    "sheet": "Blatt",
    "corporate": "Firmen-, Unternehmens-",
    "enterprise": "Unternehmen",
    "actually": "eigentlich, tatsächlich",
    "workshop": "Werkstatt",
    "faulty": "fehlerhaft, mangelhaft",
    "to join": "beitreten, mitmachen, sich jemandem anschließen, mitkommen",
    "premises": "Firmengelände",
    "to refer sb. to sb./sth.": "jemanden an jemanden/ auf etwas verweisen",
    "to implement": "ausführen, verwirklichen, realisieren",
    "Human Resources": "Personalabteilung",
    "accounting": "Buchhaltung",
    "stockkeeping": "Lagerhaltung",
    "reminder": "Erinnerung, Mahnung",
    "to match": "zuordnen",
    "purchase": "Kauf, Erwerb",
    "to assess": "bewerten, einschätzen, abschätzen",
    "faulty": "defekt",
    "customer field service": "Kundendienst",
    "enquiry": "Anfrage",
    "order": "Bestellung, Auftrag",
    "offer": "Angebot",
    "description": "Beschreibung",
    "stay": "Aufenthalt",
    "organisation chart (org chart)": "Organigramm, Organisationsschema",
    "politeness": "Höflichkeit",
    "pleasantry": "höfliche Floskel",
    "profitability": "Rentabilität",
    "to chat": "sich unterhalten",
    "health": "Gesundheit",
    "pleasant": "angenehm",
    "to waste time": "Zeit verschwenden",
    "impression": "Eindruck",
    "conference": "Tagung",
    "minutes": "Protokoll",
    "polite": "höflich",
    "usual": "gewöhnlich, üblich, normal",
    "upset": "verärgert",
    "stranger": "Unbekannte(r)",
    "on the other hand": "andererseits",
    "in charge of": "verantwortlich für",
    "cash register": "Kasse",
    "given name": "Vorname",
    "family name": "Nachname",
    "to intend": "beabsichtigen",
}

moduleTwoA = {
    "to refer to": "sich beziehen auf",
    "device": "Vorrichtung, Gerät",
    "accessories": "Zubehör",
    "projector": "Projektionsgerät, Beamer",
    "plotter": "Zeichengerät, Plotter",
    "graphic digitizer": "Grafikdigitalisierer",
    "light pen": "Lichtgriffel",
    "speaker": "Lautsprecher"
}

brexit = {
    "taxes":"Steuern, Abgaben",
    "tariffs/customs":"Zölle",
    "trade agreement":"Handelsabkommen",
    "European Union":"Europäische Union",
    "finances":"Finanzen, Geldmittel",
    "referendum":"Abstimmung, Volksbegehren, Bürgerentscheid, Referendum",
    "foreign relations":"Außenbeziehungen, Auslandsbeziehungen",
    "deal":"Abkommen, Übereinkunft",
    "failure":"Misserfolg, Scheitern, Versagen, vergeblicher Versuch",
    "decision":"Entscheidung, Beschluss, Urteil",
    "deadline":"Stichtag, Fristablauf",
    "agreement":"Vereinbarung, Einigung, Abkommen",
    "amendments":"Ergänzungen, Änderungen, Zusatzartikel zur Verfassung",
    "obstacle":"Hindernis, Hürde",
    "extension":"Erweiterung, Verlängerung",
    "delay":"Verzögerung, Verspätung",
    "to negotiate":"verhandeln, abschließen",
    "Boris Johnson":"Premierminister Vereinigtes Königreich seit 2019, Conservative Party, teilt Trumps Friseur",
    "Theresa May":"Premierministerin Vereinigtes Königreich bis 2019",
    "Nigel Farage":"Mitgründer Brexitpartei",
    "British Parliament":"Parlament des Vereinigten Königreichs",
    "Prime Minister":"Ministerpräsident",
    "Conservative Party":"Konservative Partei, mitterechts",
    "Labour Party":"Arbeitspartei, sozialdemokratisch",
    "Liberal Democrats":"Liberaldemokraten, liberal",
    "UKIP (United Kingdom Independence Party)":"Partei für die Unabhängigkeit des Vereinigten Königreichs, rechtspopulistisch",
    "Brexit Party":"Brexit-Partei, rechts",
    "protesters":"Aufbegehrende, Demonstranten",
    "protectionism":"Schutzpolitik",
    "government":"Regierung",
    "controversial":"umstritten, kontrovers",
    "resistance":"Widerstand, Abwehr, Gegenwehr",
    "gridlock":"Stillstand, festgefahrene Situation",
}


myCompany = {
    "chairman (of the board)":"Vorstandsvorsitzender",
    "device":"Gerät",
    "connection technology":"Verbindungstechnik",
    "headquarters, head office":"Hauptsitz",
    "to run a business":"ein Geschäft führen",
    "(general) partner":"aktiver Teilhaber, unbeschränkt haftender Partner",
    "purchasing":"Einkauf, Beschaffung",
    "sales":"Vertrieb",
    "Senior Vice President":"Senior-Vizepräsident",
    "mechanical engineering":"Maschinenbau",
    "component":"Bestandteil",
    "to manufacture, to produce":"anfertigen, herstellen, produzieren",
    "connector":"Stecker, Anschluss, Verbinder, Übergangsstelle",
    "automation":"Automatisierung, Automatisierungstechnik",
    "data processing":"Datenverarbeitung",
    "apprenticeship, vocational training":"Ausbildung, Berufsausbildung",
    "trainee":"Auszubildender, Praktikant",
    "sector":"Branche, Bereich, Sektor, Sparte, Markt",
    "CEO (Chief Executive Officer)":"Geschäftsführer",
    "to report to":"jemandem unterstellt sein, sich melden bei",
    "to liaise with":"mit jemandem in Kontakt sein",
    "responsibility":"Verantwortung",
    "goal strategy":"Zielstrategie",
    "organigram":"Organigramm, Organisationsschaubild",
    "platform":"Bahnsteig, Gleis, Plattform",
    "benefit":"Vorteil, Nutzen, Leistung",
    "client":"Kunde, Auftraggeber",
    "quality control, quality assurance":"Qualitätssicherung",
    "subsidiary":"Tochtergesellschaft, Niderlassung, Tochterunternehmen, Nebenstelle"
}

def fuseDicts(listOfDicts):
    output={}
    for dictio in listOfDicts:
       for key, val in dictio.items():
            if key not in output:
                output[key]=val
            else:
                output[key]=output[key]+", "+val

    return output


#ersterVokabeltest= fuseDicts([moduleOneA , amazonSheet])
#put the vocabs you actually want to practice here:
#currentVocabs=module1B
currentVocabs=fuseDicts([myCompany, brexit])
