vocabs ={
    "high-rise": "Hochhaus",
    "to range": "reichen, sich bewegen zwischen",
    "reportedly": "angeblich, wie gemeldet",
    "recent": "neu, letzte",
    "to promote": "verbreiten",
    "discriminatory practice": "diskriminierende Praxis",
    "retail": "Einzelhandel",
    "to debit": "abbuchen",
    "receipt": "Beleg, Quittung",
    "to dive into": "eintauchen",
    "mock": "Probe- / Schein-",
    "bottleneck": "Nadelöhr, Flaschenhals",
    "to defeat": "zerschlagen, besiegen",
    "intention": "Absicht",
    "line": "(Warte-)Schlange",
    "to tinker": "tüfteln",
    "counter": "Theke",
    "holdup": "Verzögerung",
    "to shrink": "schrumpfen",
    "bullish": "stur",
    "to fall short of": "hinter etwas zurückbleiben",
    "attempt": "Versuch",
    "grocery": "Lebensmittel",
    "according to": "laut",
    "permit": "Zulassung",
    "to abandon": "verlassen",
}
