vocabs = {
    "to apply": "anwenden",
    "to design": "entwerfen, konstruieren",
    "website": "Website, Internetseite",
    "to integrate": "integrieren",
    "database": "Datenbank",
    "focus": "Schwerpunkt",
    "design": "Gestaltung, Design",
    "to advise": "beraten",
    "functionality": "Funktionalität",
    "option": "Alternative, Möglichkeit",
    "benefit": "Leistung, Nutzen",
    "overall": "gesamt",
    "suggestion": "Vorschlag",
    "impact": "Wirkung, Einfluss",
    "performance": "Ergebnis, Erfolg",
    "thorough": "gründlich",
    "analytical": "analytisch",
    "verbal": "mündlich",
    "graphic": "graphisch",
    "to troubleshoot": "Fehler beheben",
    "maintenance": "Wartung",
    "LAN (local area network)": "lokales Netzwerk",
    "WAN (wide area network)": "Weitverkehrsnetzwerk",
    "implementation": "Einführung, Umsetzung, Implementierung",
    "to recommend": "empfehlen",
    "to schedule": "anberaumen",
    "to handle": "umgehen mit",
    "confidential": "vertraulich",
    "broad": "breit angelegt",
    "several": "mehrere",
    "to recognize": "erkennen, anerkennen",
    "career": "Beruf, Laufbahn, Karriere",
    "to outline": "umreißen, skizzieren",
    "systems analyst": "Systemberater",
    "findings": "Ergebnisse",
    "job title": "Berufsbezeichnung",
    "to swap": "tauschen",
    "confident": "sicher, selbstbewusst",
    "appropriate": "angemessen, passend",
    "existing": "bestehend",
    "trade fair": "Messe",
    "job fair": "Jobmesse"
}
