vocabs ={
    "apprenticeship": "Lehre, Ausbildung",
    "tutor": "Klassenlehrer, Betreuer",
    "organigram": "Organigramm",
    "curious": "neugierig",
    "major": "Haupt-, bedeutend",
    "separate": "einzeln, gesondert",
    "sheet": "Blatt",
    "corporate": "Firmen-, Unternehmens-",
    "enterprise": "Unternehmen",
    "actually": "eigentlich, tatsächlich",
    "workshop": "Werkstatt",
    "faulty": "fehlerhaft, mangelhaft",
    "to join": "beitreten, mitmachen, sich jemandem anschließen, mitkommen",
    "premises": "Firmengelände",
    "to refer sb. to sb./sth.": "jemanden an jemanden/ auf etwas verweisen",
    "to implement": "ausführen, verwirklichen, realisieren",
    "Human Resources": "Personalabteilung",
    "accounting": "Buchhaltung",
    "stockkeeping": "Lagerhaltung",
    "reminder": "Erinnerung, Mahnung",
    "to match": "zuordnen",
    "purchase": "Kauf, Erwerb",
    "to assess": "bewerten, einschätzen, abschätzen",
    "faulty": "defekt",
    "customer field service": "Kundendienst",
    "enquiry": "Anfrage",
    "order": "Bestellung, Auftrag",
    "offer": "Angebot",
    "description": "Beschreibung",
    "stay": "Aufenthalt",
    "organisation chart (org chart)": "Organigramm, Organisationsschema",
    "politeness": "Höflichkeit",
    "pleasantry": "höfliche Floskel",
    "profitability": "Rentabilität",
    "to chat": "sich unterhalten",
    "health": "Gesundheit",
    "pleasant": "angenehm",
    "to waste time": "Zeit verschwenden",
    "impression": "Eindruck",
    "conference": "Tagung",
    "minutes": "Protokoll",
    "polite": "höflich",
    "usual": "gewöhnlich, üblich, normal",
    "upset": "verärgert",
    "stranger": "Unbekannte(r)",
    "on the other hand": "andererseits",
    "in charge of": "verantwortlich für",
    "cash register": "Kasse",
    "given name": "Vorname",
    "family name": "Nachname",
    "to intend": "beabsichtigen",
}
